---
title: " Short-Term Rentals (STR) in Cambridge, MA"
output: 
  flexdashboard::flex_dashboard:
    theme: spacelab
    source_code: embed
    orientation: rows
    vertical_layout: fill
runtime: shiny
---

```{r setup, include=FALSE}
library(plyr)
library(flexdashboard)
library(shinyWidgets)
library(shiny)
library(tidyverse)
library(janitor)
library(magrittr)
library(leaflet)
library(DT)
library(plotly)
library(shinydashboard)
library(knitr)
library(htmltools)
```

```{r global, include = FALSE}
estudiantes <- read.csv2("EstudiantesUtemPregradoDiurnoDesde2014.csv",fileEncoding='latin1',check.names=F)

estudiantes <- estudiantes %>%
    mutate(latitud_campus = case_when(
            campus == "PROVIDENCIA" ~ -33.43432589824217,
            campus == "MACUL" ~ -33.466004620965656,
            TRUE ~ -33.44836932283062
      ),
          longitud_campus = case_when(
            campus == "PROVIDENCIA" ~ -70.62557864602474,
            campus == "MACUL" ~ -70.5970461754169,
            TRUE ~ -70.65829166007629
      )
    )



sexo_list <- sort(unique(estudiantes$sexo))
nacionalidad_list <- sort(unique(estudiantes$nacionalidad))
carrera_list <- sort(unique(estudiantes$carrera))
facultad_list <- sort(unique(estudiantes$facultad))
comuna_list <- sort(unique(estudiantes$comuna))


```

# Home Page {data-icon="ion-home"}

```{r}
h2("Distribución de estudiantes de la UTEM", style = "text-align:center; font-weight:bold;")
h5("Glosa H5", style = "text-align:center;")
h5("Glosa H52", style = "text-align:center;")
```

## Column {.data-width=650}

```{r include_image, echo=FALSE}
img_file <- "FondoUTEM.png"
img_div <- div(
  style = "display:flex; justify-content:center;",
  img(src = img_file, style = "max-width:100%; opacity:0.5;")
)
img_div
```

```{r}
actionButton("show_popup1", "Distribución geográfica", style = "position: absolute; top: 35%; left: 10%; width: 275px")
actionButton("show_popup2", "Distribución por carrera", style = "position: absolute; top: 55%; left: 10%; width: 275px")
actionButton("show_popup3", "Acerca de", style = "position: absolute; top: 75%; left: 10%; width: 275px")

observeEvent(input$show_popup1, {
  showModal(modalDialog(
    title = "Distribución geográfica",
    p("In this section, you can explore the spatial distribution of the Short-Term Rentals and use filters of your choice such as zipcode, STR type, property type, services listed, etc. Also, you can interact with the map, click on the icons, and learn the detailed characteristics of the STRs."),
    footer = modalButton("Close")
  ))
})

observeEvent(input$show_popup2, {
  showModal(modalDialog(
    title = "Distribución por carrera",
    p("In this section, you can perform a boxplot analysis of the Short-Term Rentals with some inputs of your choice. You can explore the distribution of a variable of interest grouped by another variable and   gain insights about the number of bedrooms, bathrooms, maximum rented capacity and more."),
    footer = modalButton("Close")
  ))
})

observeEvent(input$show_popup3, {
  showModal(modalDialog(
    title = "About",
    p("In this section, you can learn more about the definitions of the variables, explore the data source and learn more about the developers behind this dashboard."),
    footer = modalButton("Close")
  ))
})
```

# Spatial distribution {data-icon="ion-earth"}

## Inputs {.sidebar data-width="300"}

```{r}
pickerInput("sexo",
            label = "Seleccione género",
            choices = sexo_list,
            selected = sexo_list, 
            options = list(`actions-box` = TRUE),
          multiple = TRUE)
pickerInput("carrera",
            label = "Seleccione Carrera",
            choices = carrera_list,
            selected = carrera_list[1], 
            options = list(`actions-box` = TRUE,
                           `selected-text-format` = "count > 2"),
            multiple = TRUE)
pickerInput("nacionalidad",
            label = "Seleccione nacionalidad",
            choices = nacionalidad_list,
            selected = nacionalidad_list[1], 
            options = list(`actions-box` = TRUE,
                           `selected-text-format` = "count > 2"),
            multiple = TRUE)

actionButton("update1", "Update")

```

## Column

### Map of selected Short-Term Rentals

```{r}
content <- paste("<b>","Campus:","</b>",estudiantes$campus,"</br>",
                 "<b>","Ubicación:","</b>",estudiantes$latitud_campus,", ",estudiantes$longitud_campus,"</br>"
                 )
df_bar = eventReactive(input$update1, {
    estudiantes <- estudiantes %>%
      filter(sexo %in% input$sexo,
             carrera %in% input$carrera,
             nacionalidad %in% input$nacionalidad) %>%
      group_by(campus, longitud_campus, latitud_campus) %>%
      summarise(cantidad = n())
  })


renderLeaflet({
leaflet(options =leafletOptions(minZoom =11,maxZoom =16)) %>%
  #setView(lng = -71.1, lat =42.38, zoom =12) %>%
  addTiles() %>%
  addMarkers(lng = ~longitud_campus,
             lat = ~latitud_campus,
             data = df_bar(),
             popup = content) #%>%
  #addProviderTiles(providers$CartoDB.Positron) %>%
  #addMiniMap()
})


#renderPlotly({
#p1 <- ggplotly(
#  ggplot(data = df_bar(), mapping = aes(x = campus)) +
#    geom_bar()
#)
#  })



```
